name       : cryopng
version    : 0.7.5
release    : 1
source     :
    - http://downloads.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.tar.gz : 74e54b798b012dff8993fb8d90185ca83f18cfa4935f4a93b0bcfc33c849619d
license    : ZLIB
component  : system.utils
summary    : Cryopng is OptiPNG with a dirty hack perform advanced transparency cleaning.
description: |
    Cryopng is OptiPNG with a dirty hack at the libpng level to actually perform a kind of advanced "Dirty Transparency" cleaning.
    As explained by Sergey Chikuyonok (in this Smashing Magazine article) fully transparent pixels could have any RGB component since they are actually invisible, he suggested to turn them to black (0,0,0) to improve compression. A few tools have since implemented this trick (PunyPNG, PngOptimizer, ImageOptim...), but if you look closely at the PNG specifications you'll notice that images are filtered before being compressed. Cryopng turns fully transparent pixels into something that will be nullified once filtered, and this can positively affect compression.
setup      : |
    %patch -p1 < $pkgfiles/cryopng.patch
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    mv $installdir/usr/bin/optipng $installdir/usr/bin/cryopng
    mv $installdir/usr/man/man1/optipng.1 $installdir/usr/man/man1/cryopng.1
