name       : nuntius
version    : 0.2.0
release    : 1
source     :
    - https://github.com/holylobster/nuntius-linux/releases/download/v0.2.0/nuntius-0.2.0.tar.xz : 5e0b4d97aa3e4f435b8468728751d3ea58c1739f4fc3f0312693773ae89fe67e
license    : GPL-2.0
component  : desktop
summary    : Nuntius delivers notifications from your phone or tablet to your computer over Bluetooth.
description: |
    Nuntius delivers notifications from your phone or tablet to your computer over Bluetooth.

    To use Nuntius you will need to install a companion tool on your phone or tablet and pair it via Bluetooth.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
