name       : pngcrush
version    : 1.8.11
release    : 2
source     :
    - https://downloads.sourceforge.net/project/pmt/pngcrush/1.8.11/pngcrush-1.8.11-nolib.tar.xz : 23a293a9e7b1e4ea94829ae0266c8672506ed2dfa80f69b11594c650bf1ae5dd
license    : Libpng # Modified
component  : system.utils
summary    : Tool for optimizing the compression of PNG files.
description: |
    pngcrush is a free and open source command-line utility for optimizing PNG image files. It reduces the size of the file losslessly – that is, the resulting "crushed" image will have the same quality as the source image.
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %patch -p0 < $pkgfiles/makefile.patch
build      : |
    %make
install    : |
    %make_install
