name       : minecraft-overviewer
version    : 0.12.198
release    : 6
source     :
    - http://overviewer.org/builds/src/41/overviewer-0.12.198.tar.gz : a5134d414a8ffa83c23379c1b2f54ca2e42d0172fddbfcdd8991747a077c97c3
license    : GPL-3.0
component  : multimedia.graphics
summary    : A high-resolution Minecraft world renderer with a Google Maps interface
description: |
    The Minecraft Overviewer is a command-line tool for rendering high-resolution maps of Minecraft worlds. It generates a set of static html and image files and uses the Google Maps API to display a nice interactive map.
builddeps  :
    - numpy
    - python-pillow-devel
    - libpillowfight-devel
build      : |
    %python_setup
install    : |
    %python_install
