name       : minecraft-overviewer
version    : 0.12.196
release    : 5
source     :
    - http://overviewer.org/builds/src/39/overviewer-0.12.196.tar.gz : ac92d0ed1ac3d512f6063a358ff016fdfb51b663756cfd645c1eca6d4a57109e
license    : GPL-3.0
component  : multimedia.graphics
summary    : A high-resolution Minecraft world renderer with a Google Maps interface
description: |
    The Minecraft Overviewer is a command-line tool for rendering high-resolution maps of Minecraft worlds. It generates a set of static html and image files and uses the Google Maps API to display a nice interactive map.
builddeps  :
    - numpy
    - python-pillow-devel
    - libpillowfight-devel
build      : |
    %python_setup
install    : |
    %python_install
