name       : zopflipng
version    : 1.0.1
release    : 1
source     :
    - https://github.com/google/zopfli/archive/zopfli-1.0.1.tar.gz : 29743d727a4e0ecd1b93e0bf89476ceeb662e809ab2e6ab007a0b0344800e9b4
license    : Apache-2.0
component  : desktop.library
summary    : Zopfli Compression Algorithm is a compression library.
description: |
    Zopfli Compression Algorithm is a compression library programmed in C to perform very good, but slow, deflate or zlib compression.
build      : |
    %make zopflipng
install    : |
    install -Dm00755 zopflipng $installdir/usr/bin/zopflipng
