name       : jojodiff
version    : 0.8.1
release    : 1
source     :
    - http://downloads.sourceforge.net/project/jojodiff/jojodiff/jojodiff08/jdiff081.tgz : 8681e503c1d9658a89788d7e4c34c08adce5a0114610cfaaefa32f2bbe613058
license    : GPL-3.0
component  : system.utils
summary    : jojodiff is a diff utility for binary files
description: |
    jdiff is a program that outputs the differences between two (binary) files.
    jpatch can then be used to reconstruct the second file from the first file.
setup      : |
    %patch -p0 < $pkgfiles/jdefs.patch
build      : |
    pushd src/
    %make
    popd
install    : |
    pushd src/
    install -Dm00755 jdiff "${installdir}/usr/bin/jdiff"
    install -Dm00755 jptch "${installdir}/usr/bin/jptch"
    popd
