--- source/Makefile.old	2016-11-24 00:43:10.056921841 +1000
+++ source/Makefile	2016-11-24 00:47:59.443897172 +1000
@@ -5,8 +5,8 @@
 CC       = gcc
 CPP      = g++
 RC       = windres -O coff
-CPPFLAGS = -I. -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer
-LDFLAGS  = -static -static-libgcc -static-libstdc++
+CPPFLAGS ?= -I. -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer -fpermissive
+LDFLAGS  ?= -static -static-libgcc -static-libstdc++
 CSRC     = $(wildcard *.c)
 CPPSRC   = $(wildcard *.cpp)
 DEPS     = $(wildcard *.h) Makefile
