name       : digenpy
version    : 1.3.5
release    : 1
source     :
    - https://pypi.python.org/packages/48/e5/b16712c4c1ededdec0a33211eeee82c40d4d886286cacb665a839e421472/Digenpy-1.3.5.tar.gz : 720d43c86a913dc90f83d64a81f8643a7b11501d961e4e0f02b85068fce9d691
license    : GPL-2.0
component  : network.util
summary    : Python default wireless dictionary generators.
description: |
    Default password dictionary generator for multiple companys.
setup      : |
    %python_setup
install    : |
    %python_install
